@startuml
title Usecase for Information system

actor Шукач


rectangle Software {

    usecase (Отримати список житла та ресторанів)
    usecase (Отримати список позицій меню)
    
    (Отримати список позицій меню) .> (Отримати список житла та ресторанів) : include

    Шукач -- (Отримати список житла та ресторанів)
    Шукач -- (Отримати список позицій меню)
}
@enduml